import { precacheAndRoute } from 'workbox-precaching';

// Precache all the assets generated by your build process.
// Their URIs are injected by the Workbox build tool.
precacheAndRoute(self.__WB_MANIFEST);

// TODO: Add background sync strategy for API POST requests
